name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: julia-actions/setup-julia@v1
        with: 
            version: '1.5'
      - uses: julia-actions/julia-buildpkg@master
      - run: julia --project=@. -e 'using Pkg; Pkg.test("PowerModelsDistributionStateEstimation")'
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
