name: Codecov

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: julia-actions/setup-julia@v1
        with: 
            version: '1.5'
      - run: julia  --project=@. -e 'using Pkg; cd(Pkg.dir("PowerModelsDistributionStateEstimation")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
      - uses: codecov/codecov-action@v1
